import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { displayOrderStatus, listOrders, type Order } from '@/features/orders/orderService';

export default function OrderListPage() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');
  useEffect(() => { listOrders().then((items) => { setOrders(items); setStatus('ready'); }).catch(() => setStatus('error')); }, []);
  const term = search.trim().toLowerCase();
  const filtered = orders.filter((order) => [order.orderNumber, order.customerName, order.customerPhone, order.customerFlat].some((value) => value.toLowerCase().includes(term)));
  return <section className="mx-auto max-w-4xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-wide text-maroon">Admin</p><h1 className="mt-1 font-display text-3xl font-bold">Orders</h1><p className="mt-1 text-sm text-ink/60">Track every order and delivery.</p></div><Link to="/admin/orders/new" className="btn-primary w-full sm:w-auto">+ New order</Link></div><input aria-label="Search orders" type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Order ID, customer, phone or flat" className="mt-6 min-h-touch w-full rounded-card border border-ink/20 bg-white px-4 text-base" />{status === 'loading' && <p className="mt-8 text-sm text-ink/60">Loading orders...</p>}{status === 'error' && <p role="alert" className="mt-8 rounded-card bg-alert/10 p-4 text-sm text-alert-dark">Unable to load orders. Check your login and Firestore rules.</p>}{status === 'ready' && !filtered.length && <div className="card mt-8 p-6 text-center"><p className="font-semibold">{orders.length ? 'No matching orders.' : 'No orders yet.'}</p><Link to="/admin/orders/new" className="mt-4 inline-flex text-sm font-semibold text-maroon underline">Create your first order</Link></div>}<div className="mt-6 space-y-3">{filtered.map((order) => <Link key={order.id} to={`/admin/orders/${order.id}`} className="card block p-5 hover:shadow-md"><div className="flex items-start justify-between gap-4"><div><h2 className="font-display text-xl font-bold">{order.orderNumber}</h2><p className="mt-1 text-sm text-ink/65">{order.customerName} · Flat {order.customerFlat || 'not added'}</p></div><span className="rounded-pill bg-maroon/10 px-3 py-1 text-xs font-bold text-maroon">{displayOrderStatus(order.status)}</span></div><div className="mt-4 flex justify-between text-sm"><span className="text-ink/60">Due {order.expectedDeliveryDate}</span><span className="font-bold">₹{order.totalAmount}</span></div></Link>)}</div></section>;
}